baseurl = "https://jacobjbukoski.com"
title = "Jacob J. Bukoski, Ph.D."

theme = "hugo-coder-portfolio"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

DefaultContentLanguage = "en"

paginate = 20   

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

[params]
    author = "Jacob J. Bukoski, Ph.D."
    description = "Jacob Bukoski is an assistant professor in the College of Forestry at Oregon State University."
    keywords = "Jacob Bukoski, Jacob J. Bukoski"
    title = "Jacob J. Bukoski, Ph.D."

    hideCredits = true
    hideCopyright = true

    # Bottom sns share
    snsShare = true
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true
    enableFacebookShare = true
    enableHatenaShare = true
    enableLineShare = true
    enableLinkedInShare = true

    thumbnail = "./images/bukoski_tn.jpg"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false


[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "Jacob J. Bukoski, Ph.D."

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Jacob J. Bukoski"
            description = "Jacob Bukoski is an assistant professor in the College of Forestry at Oregon State University."
            keywords = "Jacob J. Bukoski, Jacob Bukoski"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "about"
                
            [[languages.en.menu.main]]
                name = "Research"
                weight = 2.0
                url = "research"
                
            [[languages.en.menu.main]]
                name = "Publications"
                weight = 3.0
                url = "publications"
                
            [[languages.en.menu.main]]
                name = "Teaching"
                weight = 4.0
               url = "teaching"
               
            [[languages.en.menu.main]]
                name = "Opportunities"
                weight = 5.0
               url = "opportunities"

#            [[languages.en.menu.main]]
#                name = "Blog"
#                weight = 5.0
#                url = "posts"


